---
  output: html_document
---
general configuration
=====================
Install and load supporting libraries.

```{r eval=TRUE, echo=FALSE}
#original data sources are available on dropbox
#/amphib_glinski_micosomes

#install.packages('rmarkdown')
#install.packages(dplyr)
#install.packages(knitr)
#install.packages(zoo)
#install.packages(xtable)
#install.packages(drc) # for fitting Michaelis Menten model
#install.packages(ggplot2) # for drawing
#library(grofit)

R.Version()$version.string
library(rmarkdown)
library(dplyr)
library(knitr)
library(zoo)
library(xtable)
library(drc) # for fitting Michaelis Menten model
library(ggplot2) # for drawing
#library(grofit)
```

import data
===========
Load csv file with experimental data. Do not have microsome data in csv format.

```{r eval=TRUE, echo=FALSE}
Sys.info()[4]

if(Sys.info()[4]=="d2626utpurucke3.aa.ad.epa.gov"){
  micro.root <- path.expand("~/git/glinski_metabolites/")
}

if(Sys.info()[4]=="DONNA-PC"){
  micro.root <- path.expand("C:/Users/Donna/Documents/Github/glinski_metabolites/")
}

if(Sys.info()[4]=="stp-air-3.local" || Sys.info()[4]=="stp-air.local"){
  micro.root <- path.expand("~/git/glinski_metabolites/")
}

micro.csv.in <- paste(micro.root, "csv_in/", sep="")
micro.csv.out <- paste(micro.root, "csv_out/", sep="")
micro.graphics <- paste(micro.root, "graphics/", sep="")
micro.tables <- paste(micro.root, "tables/", sep="")

#check to see if R can access files OK
file.exists(micro.root)
file.exists(micro.csv.in)

#import data
micro <- read.table(paste(micro.csv.in,"Microsomes2.csv",sep=""), header = TRUE, sep = ",")
```

data structure
==============
Check out structure of imported data set. Set a couple of fields as character.

```{r eval=TRUE, echo=FALSE}
str(micro)
micro$time <- factor(micro$time)
micro$tank <- factor(micro$tank)
parents <- unique(micro$parent)
analytes <- unique(micro$analyte)

micro
parents
analytes

micro.amphib <- micro[which(micro$matrix=="amphib"),]
micro.soil <- micro[which(micro$matrix=="soil"),]

#need to get actual microsome data and run michaelis menton kinetics
```
