---
  output: pdf_document
---
  michaelis-menton kinetics
========================================================
Michaelis-Menton kinetics represent an enzymatic reaction that involves competitive inhibition. An inhibitor binds to an enzme to form an inhibitor enzyme complex such that the enzyme cannot catalyze some other desired reaction.
The typical application is the determination of the rate in the presence of an inhibitor concentration 
contrasted to the rate at a different inhibitor concentration.

So we have an enzyme and a substrate that interact to from an enzyme-substrate complex that can either go back to the original enzyme and substrate or go forward to form the product and the free enzyme.
E + S <-> ES -> E + P

So for this experiment, the substrate is the pesticide, the enzyme is unknown but assumed to be present in the microsomes. Microsomes are vesicles that are formed from parts of the endoplasmic reticulum when eukaryotic cells are broken-down in the laboratory (microsomes are not present in living cells). Microsomes are then differentially centrifuged so that the soluble enzymes and cytochrome P450 are present in solution.

x <- seq(0,10,by=0.1)

curve(2*x/(1+x))

micmen <- function(x,a=2,b=1){
  a*x/(b+x)
}

curve(micmen(x), from=0, to=8, ylim=c(0,4))
